### ISSUE TITLE
Create portable Metanorma Ruby package on macOS (using ruby-packer)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#1]
Metanorma is a sophisticated document publishing tool for standardization bodies.
It is written in Ruby with a number of dependencies.

User organizations of Metanorma run on multiple platforms, including Windows, Linux and macOS.

The challenge is how to ensure the distribution and installation of Metanorma works on the target system reliably. Today, Metanorma offers:

* Ruby gem
* Linux setup script
* macOS Homebrew package
* Windows Chocolatey package
* Docker container

However, all these packages require a long installation process with caveats, such as being prone to network failures and a network of dependencies to install.

This task is to attempt to package dependencies using `ruby-packer`, a tool that packages a Ruby interpreter with gems and dependencies into a ram-disk. Our goal is to make installation quick and dependable for our users.

We are open to any other solution that can achieve this goal.

[ruby-packer] http://nts.strzibny.name/making-a-ruby-executable-with-ruby-packer/

**Comment by ronaldtse** [comment]
Our goal is to be able to run the full set on any platform, with as many cross-platform dependencies as much as we can. It could be an iterative work; I imagine that we will need some changes to ruby-packer as well.

**Comment by ronaldtse** [comment]
From @w00lf : 
> From what i have seen there is no easy way to pack all dependencies for each platform. Ruby packer only supports ruby 2.4.1 version and does not allow to pack all dependencies(Java, PlantUML and npm), the same for https://github.com/phusion/traveling-ruby or https://github.com/larsch/ocra, they can be improved, i guess, but this will require a lot of low-level programming.

> Quick update on my progress. I have cloned metanoram-cli (https://github.com/metanorma/metanorma-cli) gem and tried to pack it with ruby-packer executable. As it turns out, latest version of ruby packer only supports ruby 2.5.0 and bundler 1.15.3 - tis hardcoded in gem itself, metanorma-cli ues 2.0.1+ bundler. You said before that it has additional branches with other ruby version support, i have not found it on their github, what did you mean by that? I did found fork that supports ruby 2.6.0 https://github.com/kontena/ruby-packer but encountered a problem when tried to compile it - need some additional setup of gcc and linkers on my osx, i am going to try quickly fix it.

> I first tried created compiled version in metanorma-cli cloned gem, ruby-packer takes .gemspec in order to determine dependencies for build. I think i found the workaround to that, created executable, but now has some issues with dependent gems load, working on it now.

**Comment by ronaldtse** [comment]
@w00lf I feel that you may want to directly fork the latest ruby-packer and apply any useful PRs (https://github.com/pmq20/ruby-packer/pulls) to it. I suspect that we will need a better maintained ruby-packer to achieve what we need. Thoughts?

**Comment by w00lf** [comment]
> @w00lf I feel that you may want to directly fork the latest ruby-packer and apply any useful PRs (https://github.com/pmq20/ruby-packer/pulls) to it. I suspect that we will need a better maintained ruby-packer to achieve what we need. Thoughts?

Sure, i will fork it and see what can be taken from the original repo. Also, there is a number of interesting forks from ruby-packer original repo, for example, this repo - https://github.com/kontena/ruby-packer hash ruby 2.6.0 support.

**Comment by ronaldtse** [comment]
@w00lf I've forked the repo here: https://github.com/metanorma/ruby-packer .  Feel free to change things around (or apply additional PRs / fixes) !

**Comment by ronaldtse** [comment]
@w00lf the current arrangement of ruby-packer internalizing other projects' source code into the repo (under `/vendor`) is really strange. Could you change them to be submoduled instead? Thanks.

**Comment by w00lf** [comment]
> @w00lf the current arrangement of ruby-packer internalizing other projects' source code into the repo (under `/vendor`) is really strange. Could you change them to be submoduled instead? Thanks.

Can you please explain a little bit more? Ruby packer puts source code in this folder because it creates memory file system and needs all gems located in one folder.

**Comment by ronaldtse** [comment]
@w00lf the presence of the code in vendor/ (e.g. OpenSSL) pollutes the history. We want these changed into submodules; if we need to maintain our own forks, that's fine.

**Comment by w00lf** [comment]
> @w00lf the presence of the code in vendor/ (e.g. OpenSSL) pollutes the history. We want these changed into submodules; if we need to maintain our own forks, that's fine.

Ok, see your point now. As i understand this was done because of ruby packer maintainers use that hardcoded version of bundler and all its dependencies in order to compile executable. Thats why they were placed there in the first place. You think of separating them in standalone git module that then required in main gem? Something like ruby-packer-dependencies?

**Comment by ronaldtse** [comment]
I think there are two reasons why they were in vendor/.

1. It was easy to do and manage
2. They needed to patch the vendor codes to work with ruby-packer

But the trouble of maintaining those vendor codes inside the main repo distracts from the actual work. e.g. if one submits an OpenSSL update PR, you don't even know if those were originally from OpenSSL. I'd rather carry patches or patch the fork.

**Comment by w00lf** [comment]
Ok, got you. Will work on it after osx executable is ready.

**Comment by ronaldtse** [comment]
@w00lf this is now done, right?

**Comment by w00lf** [comment]
Yes, we can close it.

**Comment by ronaldtse** [comment]
Thanks!
