### ISSUE TITLE
Do we need an 'mnenv'?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#104]
It's generally difficult to switch metanorma versions. Terraform has `tfenv` in the same spirit as `rbenv`. Should we have an `mnenv` that uses the packed mn binaries?

Shouldn't be difficult to make?

**Comment by CAMOBAP** [comment]
interesting idea... need to think about it

**Comment by ronaldtse** [comment]
We may want this to go ahead since it’s very complex for users to manually manage versions that are working vs not working

**Comment by CAMOBAP** [comment]
According to last investigations in https://github.com/metanorma/iso-10303-2/issues/49 it sounds more then reasonable.

Key features/requirkents:
 - 0 dependencies. so we may consider PowerShell implementation for Windows and BASH (or python) implementation for other OSes
 - Support `.metanorma-version` file in local directory and user directory.
 - `mnenv install` - to install metanorma
 - `mnenv list` - to list possible options to install metanorma (binary, ruby), (--local, --remote)
 - `mnenv uninstall` - to uninstall metanorma
 - `mnenv local` - set local version
 - `mnenv global` - set global version

**Comment by ronaldtse** [comment]
@CAMOBAP very good idea and great list. Let's create a repo for that.

**Comment by ronaldtse** [comment]
Closing this since repo and new issue created.
