### ISSUE TITLE
macOS built executable crashes with reference auto-fetch from NIST

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#12]
From user:

> 1. Ran the command `brew install squashfs`
> 1. In the cloned folder I executed these commands per the `ruby-packer` instructions:
>     1. `curl -L http://enclose.io/rubyc/rubyc-darwin-x64.gz | gunzip > rubyc`
>     1. `chmod +x rubyc`
> 1. Ran `make build`
> 1. Make a document that requires auto-fetching a NIST document
> 1. Ran `./metanorma compile my-doc-with-nist-ref.adoc`

It runs and crashes with this trace.

```
fetching NIST FIPS 201 EP...
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rubyzip-2.0.0/lib/zip/central_directory.rb:143:in `get_e_o_c_d': Zip end of central directory signature not found (Zip::Error)
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rubyzip-2.0.0/lib/zip/central_directory.rb:103:in `read_e_o_c_d'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rubyzip-2.0.0/lib/zip/central_directory.rb:136:in `read_from_stream'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rubyzip-2.0.0/lib/zip/file.rb:82:in `block in initialize'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rubyzip-2.0.0/lib/zip/file.rb:81:in `open'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rubyzip-2.0.0/lib/zip/file.rb:81:in `initialize'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rubyzip-2.0.0/lib/zip/file.rb:111:in `new'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rubyzip-2.0.0/lib/zip/file.rb:111:in `open'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/hit_collection.rb:152:in `unzip'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/hit_collection.rb:130:in `data'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/hit_collection.rb:101:in `select_data'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/hit_collection.rb:86:in `from_json'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/hit_collection.rb:26:in `initialize'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/nist_bibliography.rb:17:in `new'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/nist_bibliography.rb:17:in `search'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/nist_bibliography.rb:122:in `nistbib_search_filter'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/nist_bibliography.rb:60:in `nistbib_get1'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/nist_bibliography.rb:54:in `get'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-nist-0.3.4/lib/relaton_nist/processor.rb:17:in `get'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-0.5.4/lib/relaton/db.rb:167:in `new_bib_entry'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-0.5.4/lib/relaton/db.rb:156:in `check_bibliocache'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-0.5.4/lib/relaton/db.rb:30:in `fetch'
from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.3.2/lib/asciidoctor/standoc/ref.rb:110:in `fetch_ref'
```

**Comment by ronaldtse** [comment]
> @w00lf : the enclosed memry fs is read only
> Metanorma tries to use rubyzip gem to cache generated files, this library was not patched by orginal ruby-packer maintainers so this call will not work

![image](https://user-images.githubusercontent.com/11865/67079296-3862db00-f193-11e9-8e93-ad733e27ffc7.png)

**Comment by ronaldtse** [comment]
In particular, I believe this problem only occurs when Relaton fetches the NIST document bibliography which is zipped. I'm not sure where else we use `rubyzip`.

1. @andrew2net can you help answer the above question? We want to know if it's a general issue across `metanorma` or only `relaton-nist`.
2. @w00lf could we patch `rubyzip` to fix this?

**Comment by andrew2net** [comment]
> * @andrew2net can you help answer the above question? We want to know if it's a general issue across `metanorma` or only `relaton-nist`.

@ronaldtse it's the `relaotn-nist` issue. Something is wrong with the archive.

**Comment by ronaldtse** [comment]
@andrew2net or is this an issue with `rubyzip` INSIDE the packed executable? Because the packed executable uses a read-only FS...

**Comment by andrew2net** [comment]
@ronaldtse does the file `lib/relaton_nist/data/pubs-export.zip` exist in `relaton-nist` gem? Maybe it's corrupted. Try to remove the file, then the gem will fetch another one.

**Comment by ronaldtse** [comment]
Is it trying to expand that archive in place within the gem? Because this is a read only file system, you will need to expand this in a separate tempdir provided by the system.

**Comment by ronaldtse** [comment]
And the gem should really fetch that the bibliography from nist.gov and store in computer’s relaton cache, rather than having a zip file inside the gem?

**Comment by andrew2net** [comment]
> Is it trying to expand that archive in place within the gem? Because this is a read only file system, you will need to expand this in a separate tempdir provided by the system.

The `relaton-nist` reads data from an archive and assign it to a variable. It doesn't use files to save an expanded file.
```
      Zip::File.open(DATAFILE) do |zf|
        zf.each do |f|
          @data = JSON.parse f.get_input_stream.read
          break
        end
      end
```
But I don't know about the `zip` gem. Maybe it tries to make a temp file. Suppose if it does it uses a system's tempdir.

**Comment by andrew2net** [comment]
> And the gem should really fetch that the bibliography from nist.gov and store in computer’s relaton cache, rather than having a zip file inside the gem?

We implemented the functionality https://github.com/relaton/relaton-nist/issues/20 to reduce the number of HTTP requests. We need to check the archive's date creation and get a new one then it's available and save it somewhere.
The `relaton-nist` doesn't have a cahe to save all the documents from arhive. It's used by the `relaton` to fetch documents.

**Comment by ronaldtse** [comment]
@andrew2net I found the issue. 

This code is saving the `pubs-export.zip` DIRECTLY in the local gem directory:

https://github.com/relaton/relaton-nist/blob/236d3b7b1297410df8ea492be81aea90135af8d6/lib/relaton_nist/hit_collection.rb#L13
```ruby
    DATAFILE = File.expand_path "data/pubs-export.zip", __dir__
```

This is called from the `fetch_data` method:

https://github.com/relaton/relaton-nist/blob/236d3b7b1297410df8ea492be81aea90135af8d6/lib/relaton_nist/hit_collection.rb#L136-L144


```ruby
    def fetch_data(ctime)
...
        zip = OpenURI.open_uri "https://csrc.nist.gov/CSRC/media/feeds/metanorma/pubs-export.zip"
        zip.close
        FileUtils.mv zip.path, DATAFILE
...
```

Instead of this:
```ruby
    DATAFILE = File.expand_path "data/pubs-export.zip", __dir__
```

**Comment by w00lf** [comment]
>You should save this temporary file into a relaton cache directory location.
Can you fix this ASAP? Thanks.

Ok, will create fix today

**Comment by ronaldtse** [comment]
@w00lf I think @andrew2net needs to make the fix in `relaton-nist`? He will know where to store the `relaton` cache files...

**Comment by w00lf** [comment]
> @w00lf I think @andrew2net needs to make the fix in `relaton-nist`? He will know where to store the `relaton` cache files...

Ok, got you

**Comment by w00lf** [comment]
@andrew2net tried to upgrade the application to relaton-nist 3.8.0 that contain your fixes but encountered an error in `metanorma-nist` gem:

```
No label has been processed for ID _Ref297618373
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-0.2.2/lib/isodoc/nist/word_convert.rb:270:in `block in term_cleanup': undefined method `name' for nil:NilClass (NoMethodError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:238:in `block in each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `upto'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-0.2.2/lib/isodoc/nist/word_convert.rb:268:in `term_cleanup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-0.2.2/lib/isodoc/nist/word_convert.rb:88:in `cleanup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.0.2/lib/isodoc/word_function/postprocess.rb:36:in `postprocess'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.0.2/lib/isodoc/convert.rb:169:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.0.2/lib/isodoc/word_convert.rb:34:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-0.2.2/lib/metanorma/nist/processor.rb:34:in `output'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:192:in `block in process_extensions'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:183:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:183:in `process_extensions'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:20:in `compile'
```

I was testing on samples from `mn-samples-nist`: NIST.SP.800-116r1.adoc and NIST.SP.800-126r3.adoc

**Comment by ronaldtse** [comment]
@w00lf could you update the whole Metanorma stack? metanorma-nist is already at 0.2.6 but the metanorma-nist used here is 0.2.2.

**Comment by w00lf** [comment]
> @w00lf could you update the whole Metanorma stack? metanorma-nist is already at 0.2.6 but the metanorma-nist used here is 0.2.2.

Ok, will do

**Comment by w00lf** [comment]
Update all gem dependencies to latest versions in #15
