### ISSUE TITLE
Regression: missing Linux build (required for Paneron)

### ISSUE THREAD

**Issue by strogonoff** [metanorma/packed-mn#123]
Paneron attempts to bundle Metanorma from https://github.com/metanorma/packed-mn/releases/latest/download/metanorma-linux-x64.tgz when building Linux distribution. 

For the latest release, the above link returns 404.

I’ll add a workaround to allow Paneron builds without Metanorma for now, but just FYI.

**Comment by strogonoff** [comment]
I mean, according to @ronaldtse, packed-mn releases may not contain all platforms, but what logic should Paneron use then?

E.g., if latest release is missing build for platform X, should Paneron look for an older release that has X? It would work, though if APIs change between releases it could result in inconsistent cross-platform behavior. We can presume advanced user and show MN version at build so they’re aware of what they’re getting.

**Comment by ronaldtse** [comment]
packed-mn for linux 1.5.2 is released. Closing.
