### ISSUE TITLE
(URGENT) Build failed for linux in 1.5.2

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#124]
https://github.com/metanorma/packed-mn/actions/runs/1466474915

This caused the Linux build not to release. This caused #123 .

We should probably fail all the builds if one fails (back again?)

**Comment by CAMOBAP** [comment]
Looks like some weird error which should be handled on `fontist` side.

I will report a ticket and restart CI

**Comment by CAMOBAP** [comment]
the stack trace is scarry but the issues related to:
```
The downloaded file from http://ftp.lysator.liu.se/pub/opensuse/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm doesn't match with the expected sha256 checksum 
```

So to me it looks like a temporary issue, if it will not gone after CI restart I will report a ticket

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by CAMOBAP** [comment]
three times in a row I got other error probably related to fetching relaton data

```
[relaton-w3c] ("W3C XMLSchema") fetching...
Fatal Error: undefined method `to_sym' for 404:Integer
```

```
[relaton-w3c] ("W3C REC-xml") fetching...
Fatal Error: undefined method `to_sym' for 404:Integer
```

@ronaldtse @andrew2net maybe this is some known issue?

Also is it possible to cache it? If yes which paths on FS

**Comment by ronaldtse** [comment]
This is clearly a bug in relaton-w3c. Can you file a bug?

**Comment by CAMOBAP** [comment]
@ronaldtse done https://github.com/relaton/relaton-w3c/issues/14 but I cannot assign it

**Comment by ronaldtse** [comment]
Perms fixed.

**Comment by CAMOBAP** [comment]
Restarted after fix https://github.com/metanorma/metanorma-snap/actions/runs/1503804515
Done

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
