### ISSUE TITLE
Compilation tests running too long

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#130]
Some jobs runs over 3hr30m:
https://github.com/metanorma/packed-mn/runs/4420287499?check_suite_focus=true

Yet this is only 17m:
https://github.com/metanorma/packed-mn/runs/4420287459?check_suite_focus=true

The amount of tests they run aren't that different. We need to find a way to streamline the tests. The explosion of single tests causes all the tests to run very slowly as GitHub throttles the builds from the same repo.

**Comment by ronaldtse** [comment]
Maybe add a stage in between the "build" stage and the current "test" stage, where the important tests are run first, and then the optional tests?

**Comment by CAMOBAP** [comment]
@ronaldtse good idea, what is must-pass flavors list for us?

**Comment by ronaldtse** [comment]
I think we only need: `iso, cc, un, iec, ietf, ogc, bipm, csa`.

Technically we need `itu` and `iho`. But I don't know why they keep failing.

**Comment by ronaldtse** [comment]
I think we're okay now with #132. "max-parallel" set to 3.
