### ISSUE TITLE
Remove the SSL hack: all necessary certificates are contained

### ISSUE THREAD

**Issue by alexeymorozov** [metanorma/packed-mn#138]
The hack mentioned is:

https://github.com/metanorma/packed-mn/blob/c1904865ca7e5375ecb4acbf2e5e86fe682ebb9f/bin/metanorma#L178-L186

_Originally posted by @ronaldtse in https://github.com/metanorma/ruby-packer/issues/37#issuecomment-995289618_

**Comment by ronaldtse** [comment]
Do we still need this code?
