### ISSUE TITLE
[ruby-packer]: Bundle on on macOS Monterey fails due to missing `liblibmspack.bundle`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#142]
Not sure why macOS build is failing here:

```
/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/ext/x86_64-darwin/liblibmspack.bundle': dlopen(/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/ext/x86_64-darwin/liblibmspack.bundle, 5): image not found (LoadError)
8
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `map'
9
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `ffi_lib'
10
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/lib/libmspack.rb:18:in `<module:LibMsPack>'
11
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/lib/libmspack.rb:16:in `<top (required)>'
12
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/excavate-0.3.0/lib/excavate/extractors/cab_extractor.rb:1:in `require'
13
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/excavate-0.3.0/lib/excavate/extractors/cab_extractor.rb:1:in `<top (required)>'
14
```

_Originally posted by @ronaldtse in https://github.com/metanorma/packed-mn/issues/126#issuecomment-996052797_

**Comment by ronaldtse** [comment]
From @CAMOBAP :

> @ronaldtse `liblibmspack.bundle` - looks like wrong name it should be any of `mspack.bundle` or `libmspack.bundle` maybe some logic in `ffi` gem changed

**Comment by ronaldtse** [comment]
From @ronaldtse :

The only remaining issue now is the macOS build right now failing due to `liblibmspack.bundle` not found (when running `metanorma help`).

```
2021-12-18T08:48:44.4412450Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/ext/x86_64-darwin/liblibmspack.bundle': dlopen(/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/ext/x86_64-darwin/liblibmspack.bundle, 5): image not found (LoadError)
2021-12-18T08:48:44.4415840Z 	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `map'
2021-12-18T08:48:44.4417830Z 	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `ffi_lib'
2021-12-18T08:48:44.4419920Z 	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/lib/libmspack.rb:18:in `<module:LibMsPack>'
2021-12-18T08:48:44.4422250Z 	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/lib/libmspack.rb:16:in `<top (required)>'
2021-12-18T08:48:44.4424580Z 	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/excavate-0.3.0/lib/excavate/extractors/cab_extractor.rb:1:in `require'
```

However, lo and behold, I do have this exact path in one of my installs!!

```
PATH: vendor/bundle/ruby/2.6.0/gems/libmspack-0.10.1/ext/x86_64-linux/
```
<img width="602" alt="Screenshot 2021-12-18 at 10 05 49 PM" src="https://user-images.githubusercontent.com/11865/146643848-957ff7ea-70de-46d3-8461-ba3ebd7809b6.png">

That root path has a `.bundle/config` file that has:
```sh
$ cat .bundle/config
---
BUNDLE_PATH: "vendor/bundle"
BUNDLE_CACHE_ALL: "true"
```

**Comment by ronaldtse** [comment]
This is due to this code where it tries to add the `lib` prefix:
https://github.com/ffi/ffi/blob/7c70b829ab422dceeaf472436f3a38fca6ef8f0b/lib/ffi/library.rb#L44-L55

```ruby
  def self.map_library_name(lib)
    # Mangle the library name to reflect the native library naming conventions
    lib = Library::LIBC if lib == 'c'

    if lib && File.basename(lib) == lib
      lib = Platform::LIBPREFIX + lib unless lib =~ /^#{Platform::LIBPREFIX}/
      r = Platform::IS_WINDOWS || Platform::IS_MAC ? "\\.#{Platform::LIBSUFFIX}$" : "\\.so($|\\.[1234567890]+)"
      lib += ".#{Platform::LIBSUFFIX}" unless lib =~ /#{r}/
    end

    lib
  end
```

And this is where the search happens:
https://github.com/ffi/ffi/blob/7c70b829ab422dceeaf472436f3a38fca6ef8f0b/lib/ffi/library.rb#L95-L104
```ruby
    def ffi_lib(*names)
      raise LoadError.new("library names list must not be empty") if names.empty?

      lib_flags = defined?(@ffi_lib_flags) ? @ffi_lib_flags : FFI::DynamicLibrary::RTLD_LAZY | FFI::DynamicLibrary::RTLD_LOCAL
      ffi_libs = names.map do |name|

        if name == FFI::CURRENT_PROCESS
          FFI::DynamicLibrary.open(nil, FFI::DynamicLibrary::RTLD_LAZY | FFI::DynamicLibrary::RTLD_LOCAL)

        else
```

It's possible that the `libmspack` gem uses the `ffi_lib` method incorrectly.

There we go:
https://github.com/davispuh/ruby-libmspack/blob/a17fa209923f34a69b95bbf03ed27a4677b20c5d/lib/libmspack.rb#L18
```ruby
module LibMsPack
    extend FFI::Library
    ffi_lib FFI::Compiler::Loader.find('libmspack')
```

The line `ffi_lib FFI::Compiler::Loader.find('libmspack')` should directly point to the path of the bundle file **within** the libmspack gem. 

The `FFI::Compiler::Loader.find('libmspack')` call seems to be the issue here:
https://github.com/ffi/ffi-compiler/blob/daadf48781ed2cd4f1bad51d76fd8667de9dde82/lib/ffi-compiler/loader.rb#L8-L22

To fix this issue we will need to make a PR to `ffi-compiler`.

**Comment by alexeymorozov** [comment]
As I currently see, we have [a patch](https://github.com/metanorma/packed-mn/blob/maxirmx-tebako-packager/bin/metanorma#L81) which extracts libs from memfs to file system. This patch failed to work since the path of a library starts with `__ruby_packer_memfs__` but the `COMPILER_MEMFS` constant was changed to `__tebako_memfs__`. We either need to provide tebako path for `ffi_lib`, or change the patch to handle both prefixes (tebako and ruby-packer). I'm a little out of context here.

Other things which were considered:
1. The `liblib` prefix, though it's misleading, is correct. It's generated so during compilation and used later.
2. The `FFI.ffi_lib` is used is being [patched](https://github.com/metanorma/packed-mn/blob/maxirmx-tebako-packager/bin/metanorma#L81) internally as I mentioned before, so real paths are different (real path is from a tmp dir).
3. libmspack uses the `ffi-compiler2` gem which is an already patched version of the original `ffi-compiler` gem

**Comment by alexeymorozov** [comment]
Anyway have done [a PR](https://github.com/ffi/ffi-compiler/pull/21) to `ffi/ffi-compiler`.

**Comment by ronaldtse** [comment]
> * The `liblib` prefix, though it's misleading, is correct. It's generated in such way during compilation and used later.

The `liblib` prefix is clearly an error as we can see in the original code of FFI-Compiler. It never intended to add the `lib` prefix when the provided library name already includes `lib`. i.e. this is both wrong at the compilation phase and also at the usage phase.

> The FFI.ffi_lib method is being patched internally as I mentioned before, so real paths are different (real path is from a tmp dir).

Is there a way we can simplify this?

> libmspack uses the ffi-compiler2 gem which is an already patched version of the original ffi-compiler gem

We probably should upstream all the necessary fixes rather than maintain our own ffi-compiler2 gem?

**Comment by ronaldtse** [comment]
> Anyway have done [a PR](https://github.com/ffi/ffi-compiler/pull/21) to `ffi/ffi-compiler`.

Thanks!

**Comment by alexeymorozov** [comment]
> The `liblib` prefix is clearly an error as we can see in the original code of FFI-Compiler. It never intended to add the `lib` prefix when the provided library name already includes `lib`. i.e. this is both wrong at the compilation phase and also at the usage phase.

Can do a PR to libmspack and remove the duplicate prefix.

> Is there a way we can simplify this?

I see two goals here: simplify debugging and simplify packed-mn.

Debugging can be improved by:
1. Log debug message when every time `extract_memfs` is called
2. Make extraction from both memfses
3. Try to patch `FFI::Library.ffi_lib` instead of the internal `FFI.map_library_name`
4. Try to patch `FFI::DynamicLibrary` which is a compiled C method

`packed-mn` can be simplified by:
1. isolating the patch in `ruby-packer`

I think we wouldn't need this patch after migrating to `tebako`? Since it would be incapsulated by `tebako` by directly overriding `dlopen`?

> We probably should upstream all the necessary fixes rather than maintain our own ffi-compiler2 gem?

Since we have upstreamed the fix (seems it is the last fix), can ask maintainers to do a release, and then ask a maintainer of libmspack to migrate from `ffi-compiler2` to the original one.

**Comment by ronaldtse** [comment]
> Can do a PR to libmspack and remove the duplicate prefix.

Yes please.

> I see two goals here: simplify debugging and simplify packed-mn.

Perhaps we can add these issues directly to Tebako, since @maxirmx should have Tebako for macOS ready in a few weeks.

> Since we have upstreamed the fix (seems it is the last fix), can ask maintainers to do a release, and then ask a maintainer of libmspack to migrate from ffi-compiler2 to the original one.

Ah I was not aware that ffi-compiler2 is maintained separately from the original ffi-compiler. If your fix is already upstreamed there's nothing else to be done (if the original maintainer of ffi-compiler is not active, there's nothing we can do).

**Comment by maxirmx** [comment]
I now have tebako-packaged bundle failing at MacOS because of this issue. Well, some issue related to libmspack.
Of course it is not very clear, since it crashes on 10.15/x86 (GHA),   returns reasonable error on arm86(local), but apparently works with ruby-packer.

This is the output I have
```
raceback (most recent call last):
	2: from /__tebako_memfs__/local/metanorma:193:in `<main>'
	1: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- isodoc (LoadError)
	9: from /__tebako_memfs__/local/metanorma:193:in `<main>'
	8: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	7: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	6: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	5: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc.rb:20:in `<top (required)>'
	4: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	3: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	2: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/xslfo_convert.rb:1:in `<top (required)>'
	1: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require'
/__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require': cannot load such file -- metanorma (LoadError)
	35: from /__tebako_memfs__/local/metanorma:193:in `<main>'
	34: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	33: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	32: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	31: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc.rb:20:in `<top (required)>'
	30: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	29: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	28: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/xslfo_convert.rb:1:in `<top (required)>'
	27: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	26: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	25: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	24: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma.rb:11:in `<top (required)>'
	23: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	22: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	21: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/compile.rb:5:in `<top (required)>'
	20: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	19: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	18: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.13.0/lib/fontist.rb:11:in `<top (required)>'
	17: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	16: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	15: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.13.0/lib/fontist/font.rb:1:in `<top (required)>'
	14: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	13: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	12: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.13.0/lib/fontist/font_installer.rb:2:in `<top (required)>'
	11: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	10: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 9: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate.rb:4:in `<top (required)>'
	 8: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate.rb:4:in `require_relative'
	 7: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate/extractors.rb:2:in `<top (required)>'
	 6: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate/extractors.rb:2:in `require_relative'
	 5: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.0/lib/excavate/extractors/cab_extractor.rb:1:in `<top (required)>'
	 4: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 3: from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 2: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/libmspack-0.10.1/lib/libmspack.rb:16:in `<top (required)>'
	 1: from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/libmspack-0.10.1/lib/libmspack.rb:18:in `<module:LibMsPack>'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/ffi-compiler2-2.0.1/lib/ffi-compiler/loader.rb:25:in `find': cannot find 'libmspack' library (LoadError)```

**Comment by ronaldtse** [comment]
> Of course it is not very clear, since it crashes on 10.15/x86 (GHA), returns reasonable error on arm86(local), but apparently works with ruby-packer.

The problem seems to be that the compile-time and run-time environments slightly differ. The library path is sometimes recognized as `liblibmspack` but sometimes `libmspack`.

> Can do a PR to libmspack and remove the duplicate prefix.

@alexeymorozov could you help do a PR for this? This is now blocking progress with Tebako, which we hope to have fixed soon...

**Comment by maxirmx** [comment]
libmspack gem really has an extension with the name _liblibmspack(.so, .bundle, .dll)_
This is consistent in all environments. Furthermore _liblibmspack.so_ (for ubuntu x86) and _liblibmspack.dll_ binaries are prepackaged.

MacOS issue is related to glob that libmspack uses when it does not have prepackaged binary  
Something like 
```
__ruby_packer_memfs__/local/lib/**/liblibmspack.bundle
```
I believe that in some environments ** **in the middle of the pattern** causes a sequence of ruby core calls that ruby-packer does not support.
Tebako build 0.3.0 did not support it either (https://github.com/tamatebako/tebako/issues/68) 

I will fix tebako and can probably fix ruby packer though I would rather avoid the last

**Comment by ronaldtse** [comment]
@maxirmx great work with this. 

> Furthermore liblibmspack.so (for ubuntu x86) and liblibmspack.dll binaries are prepackaged.

The funny name is just an artifact of the "library name generation code", it is supposed to be just `libmspack`.

> I will fix tebako and can probably fix ruby packer though I would rather avoid the last

We do not need to fix ruby-packer anymore.
