### ISSUE TITLE
Clean up after migration to Tebako: do we still need some ruby-packer hacks?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#157]
https://github.com/metanorma/packed-mn/blob/111c0b258f7c041b267845fb93b5f2a624039123/bin/metanorma#L220-L228

https://github.com/metanorma/packed-mn/blob/111c0b258f7c041b267845fb93b5f2a624039123/bin/metanorma#L230-L248

**Comment by maxirmx** [comment]
I guess the second hack (gems explicitly loaded) shall not be required with tebako. 
The first hack (certificates) is Windows-only.  Linux/MacOS code does not execute it.

**Comment by ronaldtse** [comment]
@maxirmx that would be wonderful. Please help remove those we don't need. Thanks!

**Comment by maxirmx** [comment]
Closed by #172
