### ISSUE TITLE
Add winget package for packed-mn

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#159]
Winget is the default command-line package manager in Windows 10.

`wingetcreator` from Microsoft to create a manifest for winget:
* https://github.com/microsoft/winget-create

* https://www.dolthub.com/blog/2021-10-13-how-to-publish-winget-chocolatey-packages-with-github-actions/
* Sample of how others package their code in winget: https://github.com/dolthub/windows-msi-creator

**Comment by ronaldtse** [comment]
Our investigation was done at https://github.com/metanorma/chocolatey-metanorma/issues/62

**Comment by CAMOBAP** [comment]
Related ticket https://github.com/metanorma/winget-metanorma/issues/1

**Comment by CAMOBAP** [comment]
https://github.com/microsoft/winget-pkgs/pull/168143

**Comment by CAMOBAP** [comment]
First package was released on winget https://github.com/microsoft/winget-pkgs/pull/168143#event-14018677917
