### ISSUE TITLE
Macos, Undefined symbols for architecture x86_64:  google::ErrnoLogMessage::ErrnoLogMessage

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#160]
During the v1.5.15 release, we faced with issue ([full logs](https://github.com/metanorma/packed-mn/actions/runs/2304713353))

```
...
linking miniruby
Undefined symbols for architecture x86_64:
  "google::ErrnoLogMessage::ErrnoLogMessage(char const*, int, int, long long, void (google::LogMessage::*)())", referenced from:
      folly::symbolizer::installFatalSignalHandler(std::__1::bitset<64ul>) in libfolly.a(SignalHandler.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
```

It doesn't seem that anything changed between `v1.5.15-pre.1` ([passed](https://github.com/metanorma/packed-mn/runs/6187551396?check_suite_focus=true) and `v1.5.15` (failed) releases. So it probably related to some third party library

According to the logs, it looks like on v1.5.15 prebuilt from cache was used while `v1.5.15-pre.1` the cache was missed

Probably CACHE_VER increment will resolve the issue, but it's not clear why it happens at all, maybe we should not cache particular deps?

**Comment by maxirmx** [comment]
With v1.5.15-pre.1   build homebrew installed **glog 0.5.0**;    when you ran v1.5.15 a couple of days later it installed **glog 0.6.0**  and it looks like it is not backwards compatible.

(This is not cached)   

I will fix it today.
