### ISSUE TITLE
Upgrade bundler version to > 2.3.3 to avoid Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#166]
Some time ago I noticed the warning message:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```

Per https://github.com/rubygems/rubygems/issues/5234 it's fixed for bundler > 2.3.3, probably it make sense to upgrade bundler

**Comment by ronaldtse** [comment]
Agree, thanks!

**Comment by ronaldtse** [comment]
@maxirmx would you be able to help with this? Thanks!

**Comment by maxirmx** [comment]
Yes, I did it in Alpine branch.
I will rebase it

**Comment by ronaldtse** [comment]
Thank you @maxirmx !
