### ISSUE TITLE
Move env settings to `.env`, (to avoid duplication) and use to read it https://github.com/marketplace/actions/dotenv-action

### ISSUE THREAD

**Issue by maxirmx** [metanorma/packed-mn#170]
I have a proposal to move those values to `.env`, (to avoid duplication) and use to read it https://github.com/marketplace/actions/dotenv-action

_Originally posted by @CAMOBAP in https://github.com/metanorma/packed-mn/pull/168#discussion_r905404872_

**Comment by ronaldtse** [comment]
Makes sense. Let's proceed.  Thanks!

**Comment by maxirmx** [comment]
This action does not set operating system environment variables.
It reads ```.env``` file and make the values available in GHA environment

If, for example, there is .env file with
```
RUBY_VER=2.7.5  
```

and apply it as
```
      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v0.2.8
```

this will make my variable accessible as 
```
${{ steps.dotenv.outputs.RUBY_VER }}
```
but not in the runner OS

**Comment by maxirmx** [comment]
I can probably fork and extend this action to push environment into runner OS
It does not look to hard, imho shalll be separated from alpine effort

**Comment by CAMOBAP** [comment]
@maxirmx https://github.com/marketplace/actions/environment-variables-from-dotenv looks more suitable because it actually provides env vars (per description)

**Comment by maxirmx** [comment]
This action is a 10-lines  bash script that runs in docker container.  
And it terminates with error that makes no sense for me.

I will fork from falti/dotenv-action@v0.2.8  and missing output.

**Comment by maxirmx** [comment]
Wait, what this action shall do is actually a one-liner:
```
cat .env >> $GITHUB_ENV
```
