### ISSUE TITLE
Add IEEE flavor test

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#173]
We have to add an IEEE test now that metanorma-ieee exists, but we do not have samples prepared for it yet.

**Comment by CAMOBAP** [comment]
Looks like we already have it https://github.com/metanorma/mn-samples-ieee

**Comment by ronaldtse** [comment]
Yes it was created afterwards. Now we just need to integrate it into our release test flow?

**Comment by CAMOBAP** [comment]
I will after passing windows 1.5.24 release
