### ISSUE TITLE
(URGENT) Windows run for packed-mn failed at latest release

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#175]
https://github.com/metanorma/packed-mn/runs/8024850532?check_suite_focus=true

The previous release contained a bug in metanorma-ogc that would fail on encountering requirements. We need to release this ASAP.

Example of this failure:
https://github.com/metanorma/ogc-GeoPose/runs/8028086129?check_suite_focus=true

**Comment by CAMOBAP** [comment]
More details:

 - Exception code: 0xc0000005 - ([memory error](https://docs.microsoft.com/en-us/previous-versions/troubleshoot/visualstudio/foxpro/c0000005-error-troubleshoot))
 - Fault offset: 0x00004052

Also for the last executable, Windows blocks the execution with:

![VirtualBox_MSEdge - Win10 clean_26_08_2022_08_28_15](https://user-images.githubusercontent.com/2169738/186850690-7f8de990-9fed-4024-bcbf-a088b9372bce.png)

I just double-checked 1.5.23, there are no such issues for it

To be continued...

 - [ ] Check `bundle install` logs


[1.5.23.bundler.log](https://github.com/metanorma/packed-mn/files/9430934/1.5.23.bundler.log)
[1.5.24.bundler.log](https://github.com/metanorma/packed-mn/files/9430935/1.5.24.bundler.log)

**Comment by CAMOBAP** [comment]
<details>
  <summary>Diff bundler log</summary>
  
  ```diff
  --- 1.5.23.bundler.log	2022-08-26 10:40:22.000000000 +0200
  +++ 1.5.24.bundler.log	2022-08-26 10:40:27.000000000 +0200
  @@ -52,7 +52,7 @@
   Installing latex-decode 0.4.0
   Fetching builder 3.2.4
   Installing builder 3.2.4
  -Using bundler 2.3.20
  +Using bundler 2.3.21
   Fetching byebug 11.1.3
   Installing byebug 11.1.3 with native extensions
   Fetching camertron-eprun 1.1.1
  @@ -164,8 +164,8 @@
   Installing optout 0.0.2
   Fetching unicode2latex 0.0.6
   Installing unicode2latex 0.0.6
  -Fetching mnconvert 1.20.0
  -Installing mnconvert 1.20.0
  +Fetching mnconvert 1.21.0
  +Installing mnconvert 1.21.0
   Fetching tokenizer 0.3.0
   Installing tokenizer 0.3.0
   Fetching metanorma-ietf-data 0.2.0
  @@ -254,8 +254,8 @@
   Installing sterile 1.0.23
   Fetching mathml2asciimath 0.0.14
   Installing mathml2asciimath 0.0.14
  -Fetching relaton-bib 1.13.0
  -Installing relaton-bib 1.13.0
  +Fetching relaton-bib 1.13.1
  +Installing relaton-bib 1.13.1
   Fetching nokogiri-styles 0.1.2
   Installing nokogiri-styles 0.1.2
   Fetching reverse_markdown 1.4.0
  @@ -318,8 +318,8 @@
   Installing relaton-iana 1.13.0
   Fetching relaton-ieee 1.13.0
   Installing relaton-ieee 1.13.0
  -Fetching relaton-ietf 1.13.0
  -Installing relaton-ietf 1.13.0
  +Fetching relaton-ietf 1.13.1
  +Installing relaton-ietf 1.13.1
   Fetching relaton-iho 1.13.0
   Installing relaton-iho 1.13.0
   Fetching relaton-nist 1.13.0
  @@ -355,9 +355,9 @@
   Installing relaton-bsi 1.13.0
   Installing relaton-gb 1.13.0
   Fetching relaton-iec 1.13.0
  -Fetching relaton-iso 1.13.0
  +Fetching relaton-iso 1.13.1
   Installing relaton-iec 1.13.0
  -Installing relaton-iso 1.13.0
  +Installing relaton-iso 1.13.1
   Fetching relaton-ogc 1.13.0
   Fetching excavate 0.3.1
   Installing relaton-ogc 1.13.0
  @@ -433,11 +433,11 @@
   Fetching metanorma-ietf 3.0.10
   Installing metanorma-ietf 3.0.10
   Fetching metanorma-itu 2.1.7
  -Fetching metanorma-ogc 2.2.1
  +Fetching metanorma-ogc 2.2.1.1
   Installing metanorma-itu 2.1.7
   Fetching metanorma-un 0.9.7
   Installing metanorma-un 0.9.7
  -Installing metanorma-ogc 2.2.1
  +Installing metanorma-ogc 2.2.1.1
   Fetching metanorma-cc 2.1.7
   Installing metanorma-cc 2.1.7
   Fetching metanorma-csa 2.1.7
  @@ -450,6 +450,6 @@
   Fetching metanorma-iec 2.1.7
   Installing metanorma-iec 2.1.7
   Installing metanorma-bipm 2.1.7
  -Fetching metanorma-cli 1.5.23
  -Installing metanorma-cli 1.5.23
  +Fetching metanorma-cli 1.5.24
  +Installing metanorma-cli 1.5.24
   Bundle complete! 10 Gemfile dependencies, 227 gems now installed.
  \ No newline at end of file
  ```
</details>

Because we are updated other deps multiple times without any issues I think that there must be something related to bundler gem update. Trying to build with `2.3.20` bundler

**Comment by CAMOBAP** [comment]
Release on the way https://github.com/metanorma/chocolatey-metanorma/actions/runs/2935317819

**Comment by ronaldtse** [comment]
@CAMOBAP did the bundler downgrade help with Windows Defender? I feel that these were due to Orca extracting out files to the temp directory.

**Comment by CAMOBAP** [comment]
@ronaldtse I think actual fix was to add back `--gemfile` + remove `require "bundler/setup"`, let me unfreeze bundler version

**Comment by CAMOBAP** [comment]
Done
