### ISSUE TITLE
All tests fail with "ERROR: Can't find header dir for ruby" message

### ISSUE THREAD

**Issue by maxirmx** [metanorma/packed-mn#178]
- This happens on all platforms including Windows (so it is not related to tebako)
- The message is generated by RubyInline gem attempting to recompile embedded C code
- RubiInline is called by png

**Comment by ronaldtse** [comment]
Thanks @maxirmx for investigating. @opoudjis do we need the png gem?

**Comment by maxirmx** [comment]
RubyInline creates a kind of binary extension for a gem (png in our case)
But the extension is created on ```require``` not on ```gem/bundle install```. 
Tebako does ```bundle install``` into pristine environment and packages whatever is created there.  So there is no binary for inlined code

**Comment by maxirmx** [comment]
I can add a custom step to tebako so that some Ruby code is executed before packaging
I guess if we call ```require png``` there it will solve the problem

**Comment by ronaldtse** [comment]
I actually wonder if we need the png gem at all in Metanorma. If not then we don't need rubyinline. However, I'm also not sure if there is a generic way of solving this.

**Comment by maxirmx** [comment]
We can have bundler plugin that implements post install hook that calls require for all gems, referencing RubyInline

**Comment by ronaldtse** [comment]
Calling "require" on all bundled gems is a reasonable requirement, for example, Opal also does that. 

As a side note, I wonder if we should also consider the bundler "vendor" mode which places all the gems in one directory that allows easy packaging.

**Comment by maxirmx** [comment]
png is outdated (2015). I use the newer gem: https://rubygems.org/gems/libpng-ruby
Sorry, I did not notice it earlier

**Comment by opoudjis** [comment]
And I have removed the png gem from standoc; it turns out we didn't need it after all.

**Comment by ronaldtse** [comment]
Great, let's get that gem removed.

**Comment by maxirmx** [comment]
I think this issue can be closed
Keeping possible improvement in #179
