### ISSUE TITLE
build.sh add test for Linux?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#18]
Do we have to fix this test?

https://github.com/metanorma/packed-mn/blob/1e81c207d5080064bc24bcf125cb7053a9e5d79a/bin/build.sh#L5-L10

_Originally posted by @ronaldtse in https://github.com/metanorma/packed-mn/pull/10_

**Comment by w00lf** [comment]
> Do we have to fix this test?
> 
> https://github.com/metanorma/packed-mn/blob/1e81c207d5080064bc24bcf125cb7053a9e5d79a/bin/build.sh#L5-L10
> 
> _Originally posted by @ronaldtse in #10_

Wrong test for the platform, fixed in https://github.com/metanorma/packed-mn/commit/9ab018038a40e3af8d8d7ce10aef273141d61e10

**Comment by ronaldtse** [comment]
Thanks @w00lf !
