### ISSUE TITLE
Failure with psych 5.x

### ISSUE THREAD

**Issue by maxirmx** [metanorma/packed-mn#198]
Psych gem 5.x abandons ```--enable-bundled-libyaml``` configuration option in this commit: https://github.com/ruby/psych/commit/447d372dcd46082ae0fdf87abead8da327177af4 

In 5.x it looks (by default ?) for locally installed libyaml and it causes failure for all tebako packages.
If we can stay with psych 4.x it can be at least a temporary solution

cc @ronaldtse @CAMOBAP

**Comment by ronaldtse** [comment]
Is there a way we can "escape" by using a bundled libyaml with Psych 5.x?

**Comment by maxirmx** [comment]
According to psych documentatio (https://github.com/ruby/psych) they support static builds from sources
It is a matter of integration into packaging process
