### ISSUE TITLE
Update to latest Tebako (was: Missing binaries for darwin in latest v1.7.4)

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/packed-mn#204]
Discovered this when trying to fix Paneron CI.

Looks like it's due to a build failure:

https://github.com/metanorma/packed-mn/actions/runs/5320120632/jobs/9634508017#step:13:2146

**Comment by maxirmx** [comment]
This is a buid failure due to incompatible fmt version installed by homebrew
It was fixed in the latest tebako build but it is a Ruby gem now so some effort is required to change packed-mn build scripts

**Comment by ronaldtse** [comment]
Thanks @maxirmx , can you please help update the build here to use the latest Tebako? Thanks!
