### ISSUE TITLE
(URGENT) Windows: packed-mn executable considered "Ransomware Program" by TrendMicro MaximumSecurity anti-virus

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#207]
This is reported by @petervwyatt (of the @pdf-association) on Windows:

![image001](https://github.com/metanorma/packed-mn/assets/11865/f18b6c09-1cce-40ad-90d4-f25eed9d3950)

This is the package published via Chocolatey.

**Comment by ronaldtse** [comment]
@maxirmx I think we can only fix this once we have Tebako working on Windows?
* https://github.com/tamatebako/tebako/issues/90

**Comment by ronaldtse** [comment]
@CAMOBAP can you also share your insights here?

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP .

@petervwyatt could we have the "export" of this log for more details? Thanks!

**Comment by maxirmx** [comment]
Ransomware is a software that denies a user  access to files by encrypting these files.
To my best understanding Ocra in production mode does not encrypt anything; just decrypts. 

I agree with @CAMOBAP. We need more details.

As for tebako/windows I still do not have confidence that I implement Windows run-time  using Linux approach. I can replicate Ocra run-time but it will likeley have similar issues with antiviruses until we understand the root cause

**Comment by ronaldtse** [comment]
We will not be able to argue the definition of what ransomware is with this TrendMicro product, so we can only see how we can work around it. Hopefully more details would help.

In any case, the problem with Orca is the extracting all executable code and data into a temporary folder, which is a performance issue as well (and there's no caching across runs). So Orca is definitely something we should replace...

**Comment by petervwyatt** [comment]
I don't want to post the log here as it has details of my PC - I will email to @ronaldtse.

**Comment by petervwyatt** [comment]
I tried un-unblocking in TrendMicro and re-rerunning `bundle exec metanorma site generate > bundle.log 2>&1` in a Windows 11 unprivileged CMD prompt and it re-triggered. I haven't saved the exception this time so it should continue to repo. Here's a fully expanded screenshot:
![image](https://github.com/metanorma/packed-mn/assets/26521615/acbe9fcc-b9ee-45a4-b800-9e45f0d0a6d5)

I also clicked "Export" but I will email it to @ronaldtse as it may have PII in it (I haven't looked yet).

**Comment by petervwyatt** [comment]
Here's the Exported CSV (button in lower right corner) - it's completely useless as its just the screen! No PII!

[Ransomware.csv](https://github.com/metanorma/packed-mn/files/12360606/Ransomware.csv)

**Comment by petervwyatt** [comment]
Windows 11 x64, Chocolatey v1.3.0 installed via an Admin PowerShell as per their instructions, then I followed Metanorma Chocolatey instructions about 3-4 months ago.

```
metanorma --version
Metanorma 1.5.11
Metanorma::Cli 1.7.5
Metanorma::Standoc 2.4.8/IsoDoc 2.5.8
Metanorma::ISO 2.4.7
Metanorma::Iec 2.2.13
Metanorma::IEEE 1.0.14
Metanorma::Ietf 3.1.8
Metanorma::Generic 2.4.4
Metanorma::BIPM 2.2.13
Metanorma::CC 2.2.12
Metanorma::Csa 2.2.12
Metanorma::IHO 0.7.13
Metanorma::UN 0.10.12
Metanorma::Ogc 2.3.13
Metanorma::ITU 2.2.14
```

**Comment by maxirmx** [comment]
Hi @petervwyatt 
Two more questions

1) On the screenshot
<img width="1366" alt="261043670-acbe9fcc-b9ee-45a4-b800-9e45f0d0a6d5" src="https://github.com/metanorma/packed-mn/assets/2081498/981c3101-264b-4535-9312-8c1391b0c9e7">

2) As far as I understood you were running ```bundle exec metanorma site generate > bundle.log 2>&1```
Can I have your site files so that I can run it and understand what metanorma is doing ?

Thank you

**Comment by petervwyatt** [comment]
That red-bordered dialog is not resizeable so I can't discover the full path. The folder's full name is `C:\Temp\share\pdfa-iso-32000-2` which is just a clone of that repo (with no git diffs).

The other blue/gray dialog with those odd-ball filenames: I'm not sure what they are. The blue info button just says "file restored" when I hover over it. When I search for the first filename shown I find it in `C:\Temp\share\pdfa-iso-32000-2\_site\documents\iso-32000-2-202x\document_a5a05648c0a9ca60_files`. I also note that these names change on each run (I assume they are temp files)..

The TrendMicro A/V is very unhelpful!

And, yes, I can ZIP up `C:\Temp\share\pdfa-iso-32000-2` and provide to you. It is in the exact state when that command completed successfully - I haven't changed anything. I will email to @ronaldtse.

**Comment by maxirmx** [comment]
Thank you

I guess it my be related to inproper handling of temp files 
https://github.com/metanorma/packed-mn/issues/120
Let me run some experiments. It would be nice if I can do it with you site.

**Comment by petervwyatt** [comment]
@maxirmx Its too big to email and too big to upload here - can I have your email please so I can share via Google Drive?

**Comment by maxirmx** [comment]
msamsonov2000 [at] gmail.com

**Comment by maxirmx** [comment]
Hi @petervwyatt 

Metanorma 1.8.4  is available at Chokolatey

I believe we have fixed the issue that you reported but I cannot be sure that it was the only or the main problem. 
To be sure that the issue has gone you have to run metanorma twice. If the second run passes Trend Micro check this is the stable fix. 

Thank you

**Comment by petervwyatt** [comment]
Will do. Will report back soon.

**Comment by petervwyatt** [comment]
For `metanorma --version`:
```
Metanorma 1.6.2
Metanorma::Cli 1.8.4
Metanorma::Standoc 2.6.0/IsoDoc 2.6.3
Metanorma::ISO 2.5.2
Metanorma::Iec 2.3.2
Metanorma::IEEE 1.1.2
Metanorma::Ietf 3.2.2
Metanorma::Generic 2.5.2
Metanorma::BIPM 2.3.2
Metanorma::CC 2.3.2
Metanorma::Csa 2.3.2
Metanorma::IHO 0.8.2
Metanorma::UN 0.11.2
Metanorma::Ogc 2.4.2
Metanorma::ITU 2.3.2
```
![image](https://github.com/metanorma/packed-mn/assets/26521615/256d6db4-f6c4-4883-979d-6a54ca4b0545)

**Comment by petervwyatt** [comment]
I'm now running a second time after saying "Trust Program"

**Comment by petervwyatt** [comment]
It now runs to completion without any further warnings. I think you fixed whatever the issue was...

**Comment by maxirmx** [comment]
Thank you, @petervwyatt

**Comment by ronaldtse** [comment]
Thank you @petervwyatt for the confirmation!

The detection false positive issue  will have to be addressed in a new packaging approach that @maxirmx is working on, called Tebako. 

Thanks all!

**Comment by ronaldtse** [comment]
We need to document the resolution mechanism ("Trust program") on our website.

**Comment by maxirmx** [comment]
@ronaldtse 
We are not code-signing Aibika package.  If we do it may eliminated the need to "Trust program" explicitly

**Comment by maxirmx** [comment]
Documentation updated requestr moved to https://github.com/tamatebako/aibika/issues/14
