### ISSUE TITLE
OCRA version

### ISSUE THREAD

**Issue by maxirmx** [metanorma/packed-mn#208]
@ronaldtse @CAMOBAP 

It looks like we are using   https://rubygems.org/gems/ocra 
and not this one: https://github.com/metanorma/ocra 

I guess if we can sign the packaged executable (https://github.com/metanorma/ocra/pull/5/files)  it will improve the treatment of metanorma  by AV engines

Please advise

**Comment by CAMOBAP** [comment]
> It looks like we are using https://rubygems.org/gems/ocra

Yep, https://github.com/metanorma/packed-mn/blob/main/Makefile.win#L26 
We have to build it from the source, right?

> I guess if we can sign the packaged executable

@maxirmx maybe you can suggest what to read or explain idea behind the "banister signature" and https://github.com/metanorma/ocra/pull/5/files ?

**Comment by maxirmx** [comment]
@CAMOBAP 
that's all that I know: https://github.com/larsch/ocra/pull/130   I believe @ronaldtse  planned to use it in order to address earler antivirus issues

As for versions, I am totally confused. I remember that 2 years ago I fixed a critical bug in metanorma/ocra fork -- https://github.com/metanorma/ocra/pull/8

**Comment by maxirmx** [comment]
Ruby gem to temporary replace ocra https://github.com/tamatebako/aibika
Should it work better ...

**Comment by ronaldtse** [comment]
Thanks @maxirmx !
