### ISSUE TITLE
Metanorma fails to delete temp files  (Windows/Ruby 3.1)

### ISSUE THREAD

**Issue by maxirmx** [metanorma/packed-mn#210]
After migration to to Ruby 3.1 from 2.7  metanorma fails to delete temporary files.  It does not look like packager issue; it is something in the application logic
[7_Test (cc).txt](https://github.com/metanorma/packed-mn/files/12445029/7_Test.cc.txt)
[7_Test (iec).txt](https://github.com/metanorma/packed-mn/files/12445030/7_Test.iec.txt)

**Comment by maxirmx** [comment]
Not sure if it is related to #207 
It is possible

**Comment by maxirmx** [comment]
I guess that the application attempts to delete temp file that is still open.
It is OK on Linux/MacOS, the file will be marked for deletetion when it is closed; it is doable on Windows but the file shall be opened/created with O_SHARE_DELETE flag

**Comment by ronaldtse** [comment]
I think it’s kind of wrong to not close the file then delete it? Is it possible to find out where that’s happening?

**Comment by maxirmx** [comment]
Should be  something like
```
file = nil
Tempfile.create do |f|
  ...
     file = f
  ...
end
f.write('...')
f.close
```

I believe _unlink_ will be called when the block is closed but the file is still in use and is deleted on _close_
On Windows it shall be _Tempfile.create("", nil, O_SHARE_DELETE)_  to delete the file

I will try to locate it

**Comment by maxirmx** [comment]
This issue is reported by isodoc tests. 

* isodoc failes to delete temp files (#210)
* ocra attempts to delete those files on the next start (https://github.com/metanorma/ocra/issues/11)
* antivirus software identifies it as a risk because ocra application seqentially deletes a folder on startup (#207)

The issue is cause by blocks like
```
      Tempfile.open([File.basename(filename, ".*"), "css"],
                    encoding: "utf-8") do |f|
        f.write(stylesheet)
        f
      end
```
