### ISSUE TITLE
“musl” is the only package for Linux

### ISSUE THREAD

**Issue by strogonoff** [metanorma/packed-mn#213]
Since 1.8.5, `https://github.com/metanorma/packed-mn/releases/latest/download/metanorma-linux-x86_64.tgz` is not available, only `https://github.com/metanorma/packed-mn/releases/latest/download/metanorma-linux-musl-x86_64.tgz` is. Is it intentional?

**Comment by ronaldtse** [comment]
Nope not intentional. There should be gcc and musl versions. 

Ping @maxirmx

**Comment by maxirmx** [comment]
The run was manually cancelled by @CAMOBAP 
I rerun it and now ```metanorma-linux-x86_64.tgz``` is there

**Comment by CAMOBAP** [comment]
@maxirmx yep I have canceled `Scheduled` run to reduce load during release, I thought that we have it just test propose...

**Comment by maxirmx** [comment]
You have cancelled macos scheduled tun but ubuntu release run 
Let me change the schedule to night hours

**Comment by maxirmx** [comment]
@CAMOBAP  I have change the schedule. Hopefully it won't interfere with regular work

**Comment by CAMOBAP** [comment]
> You have cancelled macos scheduled tun but ubuntu release run
> Let me change the schedule to night hours

Just to be on the same page what is the propose of those scheduled runs?

**Comment by maxirmx** [comment]
@CAMOBAP 
These runs are for testing purposes
There were some cases when, for example, site data changes and one of the metanorma gems hits the area not tesetd or or not supported by tebako.  So I am using these scheduled tasks to get early alert.
