### ISSUE TITLE
An error occurred while installing expressir (1.3.0), and Bundler cannot

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#217]
https://github.com/metanorma/packed-mn/actions/runs/7340057955/job/19985409854#step:7:504

**Comment by CAMOBAP** [comment]
@maxirmx i suppose after upgrade bundler this issue should gone, is that ok to upgrade bundler version on release_tag workflow?

**Comment by maxirmx** [comment]
I recommend to use Ruby 3.1 in packed-mn

**Comment by maxirmx** [comment]
I think we will drop Ruby 2.7 support in tebako
