### ISSUE TITLE
Fix Cirrus CI workflows if we need them or remove them

### ISSUE THREAD

**Issue by maxirmx** [metanorma/packed-mn#222]
After introduction of tebako-setup GHA action Cirrues-CI workflows are broken since they rely on the files that are now missing.

@ronaldtse  do we need them at all ?  Nothing is published form macos-arm64 / linux-aarch64 from this repo.

**Comment by ronaldtse** [comment]
We need to support macos-arm64 / linux-aarch64   What is the way to enable support?
