### ISSUE TITLE
Clean up Gemfile

### ISSUE THREAD

**Issue by w00lf** [metanorma/packed-mn#27]
Clean up the Gemfile completely (and remove Gemfile.lock) to only contain:

- metanorma-cli (which will require the rest)
- ~~sassc-ruby~~
- ~~ruby-jing~~ https://github.com/metanorma/packed-mn/issues/37

**Comment by ronaldtse** [comment]
And combine Gemfiles -- linux/macos and Windows Gemfiles are identical.

**Comment by CAMOBAP** [comment]
Merged
