### ISSUE TITLE
URGENT: Not able to run compiled binary

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#28]
On execution this is what it says:

```
~/Downloads/metanorma-darwin-x64 
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated ../../../../__enclose_io_memfs__/local/Gemfile.lock to version control.

If this is a development machine, remove the /__enclose_io_memfs__/local/Gemfile freeze 
by running `bundle install --no-deployment`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* metanorma-cli (~> 1.2)

You have deleted from the Gemfile:
* metanorma-cli (= 1.2.11)
```

Maybe the build mechanism is incorrect?

ping @w00lf @CAMOBAP795

**Comment by CAMOBAP795** [comment]
Hmm strange all test has been passed on 1.2.11 release https://github.com/metanorma/packed-mn/runs/634245928?check_suite_focus=true

Also, I didn't change build scripts much, let me check rubyc documentation...

**Comment by w00lf** [comment]
@ronaldtse on what release version is it?

**Comment by ronaldtse** [comment]
https://github.com/metanorma/packed-mn/releases/tag/v1.2.11

**Comment by w00lf** [comment]
> Hmm strange all test has been passed on 1.2.11 release https://github.com/metanorma/packed-mn/runs/634245928?check_suite_focus=true
> 
> Also, I didn't change build scripts much, let me check rubyc documentation...

I think this error happens because packed-mn was built with 1.2.11 version because we have GITHUB_REF env variable inside build container, but after the build these env variable does not get preserved and when we run compiled application Gemfile changes and this error occurs. @CAMOBAP795 i should have though about that before i reviewed your PR, sorry, ruby-packer does not preserve NEV variables after the build, Gemfile should be changed accordingly.

**Comment by CAMOBAP795** [comment]
@w00lf thanks for investigation, let me think about some logic which can modify Gemfile by itself for release flow

**Comment by ronaldtse** [comment]
I've removed the release binary to prevent people fro using it. Please help fix ASAP, thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse retag in progress

**Comment by CAMOBAP** [comment]
@ronaldtse for newly created release the command works

```
./metanorma-darwin-x64 help  
Commands:
  metanorma compile FILENAME                                # Compile to a metanorma document
  metanorma help [COMMAND]                                  # Describe available commands or one specific command
  metanorma list-extensions                                 # List supported extensions
  metanorma new NAME -d, --doctype=DOCTYPE -t, --type=TYPE  # Create new Metanorma document
  metanorma template-repo                                   # Manage metanorma templates repository
  metanorma version                                         # Version of the code
```

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !
