### ISSUE TITLE
Check `metanorma setup` command

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#30]
With the merge of https://github.com/metanorma/metanorma-cli/pull/139 there is now a `metanorma setup` command that installs fonts on the user's computer, at `~/.metanorma/fonts`.

In packed-mn due to the presence of path redirects, we need to ensure that these fonts can still be installed in the right path (on the host computer, not in the binary) and read from the host computer.

**Comment by CAMOBAP** [comment]
I faced with a problem 

```
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.12.2/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/ext/x86_64-darwin/liblibmspack.bundle': dlopen(/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/ext/x86_64-darwin/liblibmspack.bundle, 5): image not found (LoadError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.12.2/lib/ffi/library.rb:99:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.12.2/lib/ffi/library.rb:99:in `ffi_lib'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/lib/libmspack.rb:18:in `<module:LibMsPack>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/lib/libmspack.rb:16:in `<top (required)>'
	from /__enclose_io_memfs__/local/metanorma:89:in `require'
	from /__enclose_io_memfs__/local/metanorma:89:in `<main>'
```

I tried to apply the similar fix https://github.com/metanorma/packed-mn/blob/master/bin/metanorma#L31-L38 for `liblibmspack.bundle` unfortunately it doesn't work, issue stay the same

@w00lf is it required that gem with native extensions must rebuild again? I'm asking because https://rubygems.org/gems/libmspack/versions/0.1.0 comes with prebuilt binaries

**Comment by w00lf** [comment]
> I faced with a problem
> 
> ```
> /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.12.2/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/ext/x86_64-darwin/liblibmspack.bundle': dlopen(/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/ext/x86_64-darwin/liblibmspack.bundle, 5): image not found (LoadError)
> 	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.12.2/lib/ffi/library.rb:99:in `map'
> 	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.12.2/lib/ffi/library.rb:99:in `ffi_lib'
> 	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/lib/libmspack.rb:18:in `<module:LibMsPack>'
> 	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/lib/libmspack.rb:16:in `<top (required)>'
> 	from /__enclose_io_memfs__/local/metanorma:89:in `require'
> 	from /__enclose_io_memfs__/local/metanorma:89:in `<main>'
> ```
> 
> I tried to apply the similar fix https://github.com/metanorma/packed-mn/blob/master/bin/metanorma#L31-L38 for `liblibmspack.bundle` unfortunately it doesn't work, issue stay the same
> 
> @w00lf is it required that gem with native extensions must rebuild again? I'm asking because https://rubygems.org/gems/libmspack/versions/0.1.0 comes with prebuilt binaries

The problem here is that ruby native extensions load methods does not work with patched ruby packer paths, e.g. starting with `/__enclose_io_memfs__/`. You need to reference them from the real file system, the hack that you saw in https://github.com/metanorma/packed-mn/blob/master/bin/metanorma#L31-L38 is actually 2 step hack: the second part is in forked sassc gem: https://github.com/metanorma/sassc-ruby/blob/master/lib/sassc/native.rb#L11, the way it works is like this: the patched version of sassc looks into the current directory for `libsass.so` file and in the metanorma script we copy `libsass.so`  from compiled fs into the current directory.

**Comment by CAMOBAP** [comment]
@w00lf thanks for the explanation, I will proceed with a patch for this line https://github.com/davispuh/ruby-libmspack/blob/f5700d5a3a1638c846af9a041f64fbe219f5936e/lib/libmspack.rb#L18 this line need to be patched, right?

**Comment by w00lf** [comment]
> https://github.com/davispuh/ruby-libmspack/blob/f5700d5a3a1638c846af9a041f64fbe219f5936e/lib/libmspack.rb#L18

Yes, that's correct. You need to change it so that it references local path instead.

**Comment by CAMOBAP** [comment]
@w00lf one more question regarding this workaround, as far as I understand it, ideally it must be fixed on the ruby-packer side. According to [ruby-packer's README.md](https://github.com/pmq20/ruby-packer)

> ...
> Native C extensions are fully supported
> ...

Also, I have found https://github.com/pmq20/ruby-packer/issues/46 it looks like the same problem which we are faced with, can you confirm this?

If no, should we report an issue to https://github.com/pmq20/ruby-packer ?

**Comment by w00lf** [comment]
> pmq20/ruby-packer#46

Yes, it seems it seems like a similar issue. The thing with ruby-packer is that it's not actively maintained at all now, the latest release was almost 3 years ago and there is no answers from devs in issues so I don't think they will help us here.

**Comment by CAMOBAP** [comment]
Paused because of https://github.com/metanorma/packed-mn/issues/6

**Comment by CAMOBAP** [comment]
Library loading issue solved in https://github.com/metanorma/packed-mn/pull/40

But for now, we have another problem, it doesn't relate to ruby-packer

```
Metanorma has detected that you do not have the necessary fonts installed
for PDF generation. The generated PDF will use generic fonts that may not
resemble the desired styling. Metanorma can download these files for you
if you accept the font licensing conditions for the font CALIBRI.TTF.

If you want Metanorma to download these fonts for you and indicate your
acceptance of the font licenses, type "Yes" / "No": Yes

Downloads: 60MB/60MB (100.00%)/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/lib/libmspack/mscab.rb:695:in `extract': 2 (LibMsPack::Exceptions::LibMsPackError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:51:in `extract_ppviewer_cab_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:56:in `cabbed_fonts'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:39:in `block in extract_ppviewer_fonts'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:38:in `tap'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:38:in `extract_ppviewer_fonts'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:21:in `fetch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:17:in `fetch_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/installer.rb:34:in `download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/installer.rb:10:in `download'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/installer.rb:16:in `download'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:63:in `ask_user_and_download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:45:in `rescue in download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:43:in `download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:23:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:16:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/command.rb:80:in `block in setup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/command.rb:79:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/command.rb:79:in `setup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli.rb:74:in `start'
	from /__enclose_io_memfs__/local/metanorma:104:in `<main>'
```

Debugging...

**Comment by CAMOBAP** [comment]
This happens because of missing `assets/ppviewer.cab` file. https://github.com/fontist/fontist/issues/29 - reported

**Comment by CAMOBAP** [comment]
Done
