### ISSUE TITLE
Release of metanorma-cli not triggering build for packed-mn

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#32]
Need to check why.

**Comment by CAMOBAP** [comment]
Composite problem:
 - [x] metanorma-cli wasn't driggered by tags https://github.com/metanorma/metanorma-cli/commit/891dcec85c80e44745136e67c041dc53b867f9ad
 - [ ] after some update on github action push --tags doesn't work, investigation in progress

**Comment by ronaldtse** [comment]
@CAMOBAP how can this be the case?

> metanorma-cli wasn't triggered by tags

Also, 
> simulate the dispatch_repository event from metanorma-cli with our trigger-gh-actions.sh script from metanorma-build-scripts repo

Is there an existing GitHub Actions action that does triggering? Thanks.

**Comment by CAMOBAP** [comment]
According to https://github.community/t5/GitHub-Actions/Github-actions-workflow-not-triggering-with-tag-push/m-p/39772#M3959 it looks like expected behavior

@ronaldtse could you please create personal access token (PAT token) and we will use it for making tag commits

If we have some special user for this propose it will be nice because this user will be shown in all releases

**Comment by CAMOBAP** [comment]
> how can this be the case?

As you may see it was https://github.com/metanorma/metanorma-cli/commit/891dcec85c80e44745136e67c041dc53b867f9ad

> Is there an existing GitHub Actions action that does triggering?

Yes but it doesn't fit our needs, metanorma-cli send dispatch_repository to many repos. Existing actions support only one dispatch_repository per step, so we need duplicate as many steps as we need

**Comment by ronaldtse** [comment]
> could you please create personal access token (PAT token) and we will use it for making tag commits

Sure, in which repos do we need this PAT_TOKEN?

**Comment by ronaldtse** [comment]
> Yes but it doesn't fit our needs, metanorma-cli send dispatch_repository to many repos. Existing actions support only one dispatch_repository per step, so we need duplicate as many steps as we need

Can we make a GitHub Action for this that triggers multiple repositories? Thanks.

**Comment by CAMOBAP** [comment]
> Sure, in which repos do we need this PAT_TOKEN?

We need it for all repos which doing `git tag`, so the list will be 

 - https://github.com/metanorma/homebrew-metanorma
 - https://github.com/metanorma/metanorma-docker
 - https://github.com/metanorma/chocolatey-metanorma
 - https://github.com/metanorma/packed-mn
 - https://github.com/metanorma/metanorma-snap

> Can we make a GitHub Action for this that triggers multiple repositories? Thanks.

Yes for sure but to be on the same page, there is no problem with https://github.com/metanorma/metanorma-build-scripts/blob/master/trigger-gh-actions.sh at this moment. This script doing his job perfectly. We have problem that if we do push commi/tag with `GITHUB_TOKEN` it cannot trigger other workflow as described here https://github.community/t5/GitHub-Actions/Github-actions-workflow-not-triggering-with-tag-push/m-p/39772#M3959

Also, I will need to know GH user name which related to this PAT_TOKEN to use his name as a committer name

**Comment by ronaldtse** [comment]
@CAMOBAP the secret `METANORMA_CI_PAT_TOKEN` is now available in all those five repos.

The username is `metanorma-ci`.

**Comment by CAMOBAP** [comment]
Just updated this repo & it works, I will propagate this to other repos

@ronaldtse I forgot about one more repo https://github.com/metanorma/mn2pdf-ruby could you please add PAT_TOKEN to it also

**Comment by CAMOBAP** [comment]
Done

@ronaldtse may I ask you to double-check https://github.com/metanorma/chocolatey-metanorma because it reports that metanorma-ci have no permissions for chocolatey-metanorma

**Comment by CAMOBAP** [comment]
Formally this task is done but https://github.com/metanorma/packed-mn/issues/33 was discovered

@w00lf may I ask you to have a look?
