### ISSUE TITLE
Linux failure

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#33]
https://github.com/metanorma/packed-mn/actions/runs/105736571

```
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
```

**Comment by w00lf** [comment]
> https://github.com/metanorma/packed-mn/actions/runs/105736571
> 
> ```
> clang: error: unable to execute command: Killed
> clang: error: clang frontend command failed due to signal (use -v to see invocation)
> clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
> clang: note: diagnostic msg: 
> ```

@CAMOBAP compilation exceeded allowed by github actions maximum time, what have you changed recently in build?

**Comment by CAMOBAP** [comment]
The first time it started on 1.2.12 release https://github.com/metanorma/packed-mn/actions/runs/95231998

Probably the only way is to increase the time https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes

**Comment by w00lf** [comment]
> https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes

Oh, that's nice, let's try this. The reason why it is running so slowly is that ruby packer uses a lot of memory so we were forced to use swap. let's see if it can compile in 2 hours.

**Comment by w00lf** [comment]
Funny thing is that osx build runs just like it is, no additional tweaks required, no swap needed.

**Comment by CAMOBAP** [comment]
Hmm, looks like a problem with RAM, @w00lf how do you think it we will increase swap, can this help?

**Comment by w00lf** [comment]
> Hmm, looks like a problem with RAM, @w00lf how do you think it we will increase swap, can this help?

ok, currently that's 4 Gb of swap, github actions box has 14Gb SSD disk available total, we can try to increase it to 10

**Comment by CAMOBAP** [comment]
Looks like it works)
