### ISSUE TITLE
Add Linux binary release 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#43]
In the latest release we only have macOS. Need to add Linux.

**Comment by CAMOBAP** [comment]
We have this logic already:

https://github.com/metanorma/packed-mn/blob/master/.github/workflows/build.yml#L100

For past two releases, CI for Linux was failed, this is why Linux binary is missed
 - 1.2.12 https://github.com/metanorma/packed-mn/actions/runs/105741117
 - 1.2.11 https://github.com/metanorma/packed-mn/actions/runs/95231998

@ronaldtse let me know if I should add those binaries manually

**Comment by ronaldtse** [comment]
@CAMOBAP We need to return the latest binary, so only 1.2.12. Thanks!

**Comment by CAMOBAP** [comment]
Done manually for 1.2.12, for new releases it will work automatically
