### ISSUE TITLE
Broken usage of sassc in 1.3.2

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#53]
```
Error: File to import not found or unreadable: base_style/all.
        on line 29:1 of stdin
>> @import 'base_style/all';

   ^
```

**Comment by ronaldtse** [comment]
This is the macOS build. This can be tested using https://github.com/CalConnect/csd-vpoll

```sh
curl -L https://github.com/metanorma/packed-mn/releases/download/v1.3.2/metanorma-darwin-x64 -o metanorma
chmod +x metanorma
./metanorma compile sources/cc-51006.adoc
```

(also happens with Linux build)

**Comment by CAMOBAP** [comment]
This happens because of fix was merged after 1.3.2 tag, I will retag

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP ! Please let me know once fixed.

**Comment by CAMOBAP** [comment]
Waiting for https://github.com/metanorma/packed-mn/actions/runs/171098198

**Comment by ronaldtse** [comment]
Seems that the build failed?

**Comment by CAMOBAP** [comment]
@ronaldtse as far as I see the only osx failed because of network issue on mn-samples-gb, let's wait for Linux job finish

**Comment by CAMOBAP** [comment]
restarted jobs

@ronaldtse I propose to split the single workflow file because currently, GHA doesn't allow to rerun for failed jobs only, it will rerun all jobs in the scope of the same workflow

**Comment by ronaldtse** [comment]
@CAMOBAP agree. It is an annoyance indeed...

**Comment by ronaldtse** [comment]
Verified -- it works. Thanks!
