### ISSUE TITLE
Failed build in 1.3.4 (since 1.3.3.1)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#57]
Notice it is due to a 50+ mins timeout.

https://github.com/metanorma/packed-mn/runs/911533542?check_suite_focus=true

```
2020-07-26T11:39:48.4345493Z compiling prelude.c
2020-07-26T12:35:05.7850994Z clang: error: unable to execute command: Killed
2020-07-26T12:35:05.8170203Z clang: error: clang frontend command failed due to signal (use -v to see invocation)
2020-07-26T12:35:05.8213899Z clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)
2020-07-26T12:35:05.8218477Z Target: x86_64-pc-linux-gnu
2020-07-26T12:35:05.8218902Z Thread model: posix
2020-07-26T12:35:05.8222460Z InstalledDir: /usr/bin
2020-07-26T12:35:05.8225486Z clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
```

**Comment by CAMOBAP** [comment]
It failed because of the list of issues:
 - clang timeout (Linux only), working on it
 - mn-samples-nist compilation because of bug (all workflows affected) https://github.com/metanorma/metanorma-nist/issues/224

**Comment by ronaldtse** [comment]
@CAMOBAP now the build is only failing on Linux.

**Comment by CAMOBAP** [comment]
@w00lf maybe you have rubyc for Linux locally, if so could you please share upload it to https://github.com/metanorma/ruby-packer/releases/tag/v0.4.0 as rubyc-linux-x64

**Comment by CAMOBAP** [comment]
Compiled Linux version with 

```
    - name: build rubyc
      run: |
        git clone https://github.com/pmq20/ruby-packer.git
        cd ruby-packer
        git checkout 90cc0d7678a04b401b168c46d598199512638d8d
        env CPPFLAGS="-P" ruby bin/rubyc bin/rubyc
    - uses: actions/upload-artifact@v2
      with:
        name: rubyc-linux-x64
        path: ruby-packer/a.out
```

Added just in case

**Comment by CAMOBAP** [comment]
Waiting for CI

**Comment by CAMOBAP** [comment]
Summary of observed issues:
 1. end of file reached (Down::ConnectionError) - happens from time to time on font install step
 2. memory issue on Linux container when compiling with clang, even with 8gb swap, for some reason after 1.3.3 of metanorma-cli gem size increased +50Mb (from 14Mb to 66Mb)

To be continued...

**Comment by ronaldtse** [comment]
@CAMOBAP re: 

> 1. end of file reached (Down::ConnectionError) - happens from time to time on font install step

I have updated/released the Fontist gem so it now fetches from a more reliable source. Is this issue still around?

> 2. memory issue on Linux container when compiling with clang, even with 8gb swap, for some reason after 1.3.3 of metanorma-cli gem size increased +50Mb (from 14Mb to 66Mb)

Ping @w00lf ?

**Comment by CAMOBAP** [comment]
@ronaldtse @w00lf regarding the second problem, I have confirmed with @opoudjis that there are no problem metanorma-cli gem size it is expected size

Also, I have one more idea to test, on ubuntu `make` runs with `j4` for some reason, but according to the specs actual machine are `2-core CPU`, I will try this if `9g` will not work

**Comment by CAMOBAP** [comment]
Also I noted that because metanorma-cli is bigger then previously we often get:

```
/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/rubyc/rubyc_work_dir/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/cache/metanorma-cli-1.3.4.gem.
It may be corrupted.
An error occurred while installing metanorma-cli (1.3.4), and Bundler cannot
continue.
```

Not only for this repo but for any `gem install metanorma-cli`

**Comment by CAMOBAP** [comment]
`make -j2` doesn't help, at the moment I'm running out of new ideas

@w00lf @ronaldtse if you have any idea, please let me know, at this point, I see the only solution - reduce the size of metanorma-cli

**Comment by ronaldtse** [comment]
I don't understand why metanorma-cli includes gems inside the gem? It's not supposed to include any gem...? AH Maybe it is something to do with the build process -- the new "gemspec" may have included files it should not have included?

**Comment by CAMOBAP** [comment]
> I don't understand why metanorma-cli includes gems inside the gem?  It's not supposed to include any gem...?

this was a surprise for me too

https://rubygems.org/gems/twitter_cldr isn't big by itself looks like it downloads resources on-demand, but why are they being packed?

I have checked https://github.com/twitter/twitter-cldr-rb issues but didn't found anything relevant...

**Comment by w00lf** [comment]
> `make -j2` doesn't help, at the moment I'm running out of new ideas
> 
> @w00lf @ronaldtse if you have any idea, please let me know, at this point, I see the only solution - reduce the size of metanorma-cli

Recently we released new versions of gems without sassc dependency, instead of it we are packing compiled css files into flavors, this could be the reason why metanorma-cli size increased drastically. Changes were performed almost for each flavor, so compiled css files added for each gem.

**Comment by w00lf** [comment]
@ronaldtse @CAMOBAP although i did check one of the flavor size - metanorma-ogc, there is no much difference in size:
Old version:
```
 du -h -d 1 /Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.0
 12K	/Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.0/bin
 12K	/Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.0/.github
2,6M	/Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.0/lib
2,6M	/Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.0
```

New version:
```
 du -h -d 1 /Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.3
 12K	/Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.3/bin
 12K	/Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.3/.github
2,7M	/Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.3/lib
2,8M	/Users/mitaraskin/.rvm/gems/ruby-2.5.3/gems/metanorma-ogc-1.1.3
```

**Comment by ronaldtse** [comment]
@w00lf I don't think the stylesheets are the issue. 

In fact, I see tons of shit inside metanorma-cli release:

```
du ~shx ~/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.3.4/
05-020r26.rxl          LICENSE                a.rb                   csd-tofix.zip          i18n.yaml              sourcecode/
05-020r26.xml.zip      README.adoc            a.rxl                  exe/                   lib/                   templates/
CODE_OF_CONDUCT.md     Rakefile               b                      extract/               metanorma-cli.gemspec  test.rxl
Gemfile                a                      bin/                   files.zip              relaton/               tmp/
Gemfile.lock           a.json                 csd-tofix 2.zip        gems/                  rice.rxl               
```

This is a problem with the release process. Ping @opoudjis . We need to re-release this gem.

**Comment by opoudjis** [comment]
Done

**Comment by ronaldtse** [comment]
Thanks @opoudjis ! @CAMOBAP can you he’ll check this issue again?

**Comment by CAMOBAP** [comment]
@ronaldtse build was started automatically https://github.com/metanorma/packed-mn/runs/953618869?check_suite_focus=true, so far build step passed, waiting for samples compilation

**Comment by CAMOBAP** [comment]
BTW that's impressive:

```
1.3.5 - August 06, 2020 (29.5 KB)
1.3.4 - July 29, 2020 (69.9 MB)
```

@opoudjis good job

**Comment by ronaldtse** [comment]
All done!! Closing now. Thank you guys!
