### ISSUE TITLE
Sassc fork, ffi_lib lookup issue

### ISSUE THREAD

**Issue by w00lf** [metanorma/packed-mn#6]
Currently, build uses forked version of gem sassc, it was done this way because ruby-packer does not know how to properly handle ffi_lib ruby call - https://github.com/w00lf/sassc-ruby/blob/master/lib/sassc/native.rb#L11. Ruby packer uses patched Dir and File classes that redirect all call to fs starting with path /__enclose_io_memfs__/ to memory filesystem, however, this is not the case for ffi_lib call. Currently, forked version performs a lookup of libsass.bundle file in the current directory, which is not the best way to handle it.

**Comment by ronaldtse** [comment]
@w00lf could you have those forks setup under the metanorma account? That would make it easier for us to manage all code under one umbrella. Thanks!

**Comment by w00lf** [comment]
> @w00lf could you have those forks setup under the metanorma account? That would make it easier for us to manage all code under one umbrella. Thanks!

Sure, Ronald, will do.

**Comment by w00lf** [comment]
> @w00lf could you have those forks setup under the metanorma account? That would make it easier for us to manage all code under one umbrella. Thanks!

Mooved in #11

**Comment by CAMOBAP** [comment]
@w00lf @ronaldtse how do you feel if we will 'patch' `ffi_lib` implementation with this approach http://ndlib.github.io/practices/responsible-overwriting-of-ruby-methods/ to accomplish the redirect to `/enclose_io_memfs/`

Will it works?

**Comment by ronaldtse** [comment]
@CAMOBAP maybe overriding that method can work for libraries that use ffi. Does sassc use ffi?

**Comment by CAMOBAP** [comment]
@ronaldtse as far as I remember yes, and we have problem only for those gems which use `ffi`

**Comment by ronaldtse** [comment]
@CAMOBAP I just re-read the initial issue, and it seems this is the correct way to go.

**Comment by w00lf** [comment]
> @ronaldtse as far as I remember yes, and we have problem only for those gems which use `ffi`
> 
> @w00lf please confirm (or not)

Yes, the main problem is with ffi load of shared libraries, in case of sassc its libsass. Ffi include cannot work with compiled in-memory fs of ruby packer.

**Comment by CAMOBAP** [comment]
Done
