### ISSUE TITLE
packed-mn not generating PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#62]
`mn2pdf` doesn't seem to be able to run in packed-mn:

```
Metanorma XML Syntax: (XML Line 000061:7): element "ics" incomplete; missing required element "text"
Metanorma XML Syntax: (XML Line 000148:79): attribute "type" not allowed here; expected attribute "inline-header", "language", "obligation" or "script"
Metanorma XML Syntax: (XML Line 000135:125): IDREF "foreword" without matching ID
Metanorma XML Syntax: (XML Line 000135:125): IDREF "foreword" without matching ID
/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/d20200909-26866-53ogb3/mn2pdf.jar
java -Xss5m -Xmx1024m -jar /var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/d20200909-26866-53ogb3/mn2pdf.jar --xml-file "mn-samples-iso/sources/international-standard/rice-en.cd.presentation.xml" --xsl-file "/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-iso-1.5.5/lib/isodoc/iso/iso.international-standard.xsl" --pdf-file "mn-samples-iso/sources/international-standard/rice-en.cd.pdf"

```
ll mn-samples-iso/sources/international-standard/ | grep -v adoc
total 2336
drwxr-xr-x   4 me  staff   128B Sep  9 15:51 body/
drwxr-xr-x   8 me  staff   256B Sep  9 15:51 images/
-rw-r--r--   1 me  staff   186K Sep  9 15:58 rice-en.cd.alt.html
-rw-r--r--   1 me  staff   296K Sep  9 15:58 rice-en.cd.doc
-rw-r--r--   1 me  staff    26K Sep  9 15:58 rice-en.cd.err
-rw-r--r--   1 me  staff   188K Sep  9 15:58 rice-en.cd.html
-rw-r--r--   1 me  staff   211K Sep  9 15:58 rice-en.cd.presentation.xml
-rw-r--r--   1 me  staff   2.3K Sep  9 15:58 rice-en.cd.rxl
-rw-r--r--   1 me  staff   208K Sep  9 15:58 rice-en.cd.xml
drwxr-xr-x  19 me  staff   608B Sep  9 15:51 sections-en/
drwxr-xr-x  19 me  staff   608B Sep  9 15:51 sections-zh/ 
```

There is no `mn-samples-iso/sources/international-standard/rice-en.cd.pdf`. Looks like the problem is that `--xsl-file "/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-iso-1.5.5/lib/isodoc/iso/iso.international-standard.xsl"` needs to be copied out to the local file system before running.

**Comment by ronaldtse** [comment]
Looks like it was supposed to be handled by this:
https://github.com/metanorma/packed-mn/blob/4f7dd68af20b9ed4ffae9dbb9acbea8531536804/bin/metanorma#L103-L112

But maybe the method name/signature changed?

Ping @CAMOBAP since this was your code 😉

**Comment by ronaldtse** [comment]
Urgent, ping @CAMOBAP

**Comment by CAMOBAP** [comment]
@ronaldtse on it

**Comment by CAMOBAP** [comment]
Per logs:

"""
java -Xss5m -Xmx1024m -jar /var/folders/9_/plmb2sws0k1_8s29w7d6hqfh0000gn/T/d20200911-76722-1a866bu/mn2pdf.jar --xml-file "test-csd.presentation.xml" --xsl-file "/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-csa-1.6.2/lib/isodoc/csa/csa.standard.xsl" --pdf-file "test-csd.pdf"
"""

for some reason xsl files weren't unpacked, research still in progress

**Comment by ronaldtse** [comment]
Correct, thanks for following up @CAMOBAP !

**Comment by CAMOBAP** [comment]
The problem with "quotes". The fix on the way
