### ISSUE TITLE
Notify snap, homebrew and chocolatey repositories

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#66]
We decided to use packed-mn instead of gem in our end-user tools

So we need replace `metanorma/metanorma-cli` with `metanorma/packed-mn` in https://github.com/metanorma/chocolatey-metanorma/blob/master/.github/workflows/release-tag.yml#L5

And modify current workflow in this repo to send `dispatch_repository`

**Comment by ronaldtse** [comment]
Agree, thanks @CAMOBAP !

**Comment by CAMOBAP** [comment]
Done
