### ISSUE TITLE
Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/. 

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#71]
https://github.com/metanorma/packed-mn/runs/1549962965?check_suite_focus=true#step:12:12816

> Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.  There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.

**Comment by CAMOBAP** [comment]
I will try update certs from https://curl.haxx.se/docs/caextract.html

**Comment by CAMOBAP** [comment]
Well the fix pushed in out own form here https://github.com/metanorma/ruby-packer/releases/tag/v0.4.1

I successfully compiled macos `rubyc` but still fighting with Linux one

BTW I have tried last released rubyc but it's broken because of https://github.com/pmq20/ruby-packer/issues/75

**Comment by CAMOBAP** [comment]
Fixed

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
