### ISSUE TITLE
Replace default ruby icon with metanorma icon

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#79]
Windows metanorma app contains the default ruby icon.

cc @ronaldtse

**Comment by ronaldtse** [comment]
Can we use this? <img width="98" alt="Screenshot 2021-02-23 at 12 50 40 AM" src="https://user-images.githubusercontent.com/11865/108740957-2eb06b00-7571-11eb-96f7-03fc8b85b089.png">

**Comment by ronaldtse** [comment]
What file formats and dimensions do we need? Will try too provide.

**Comment by CAMOBAP** [comment]
@ronaldtse thanks I will convert it to ico if need. It's not clear yet which format should be there I will check https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons first

this PNG will be enough for start

**Comment by CAMOBAP** [comment]
Done
