### ISSUE TITLE
Nist failed for 1.4.8 release

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#95]
https://github.com/metanorma/packed-mn/actions/runs/828658501

I will investigate but, to be on the same page @ronaldtse should we have nist support in 'reglar' packed-mn build?

**Comment by ronaldtse** [comment]
@CAMOBAP let's include NIST in regular build for now, we should split it off later.

**Comment by CAMOBAP** [comment]
This problem exists for regular metanorm, so this one isn't packed-mn specific. I have reported ticket https://github.com/relaton/relaton-bib/issues/46

**Comment by CAMOBAP** [comment]
Fixed in relaton 1.8.0, release restarted

**Comment by CAMOBAP** [comment]
- win & osx passed, will reopen if linux will fail
